### ISSUE TITLE
pass the wrong type of optional arguments of the tool

### ISSUE THREAD

**Issue by zxkane** [wong2/mcp-cli#1]
The [MCP server](https://github.com/zxkane/mcp-server-amazon-bedrock) has a tool, which requires some optional arguments.

CLI calls the tool with optional arguments as an empty string that is rejected by the server's validation. And CLI can not pass the number value of argument in the tool call.

**Comment by wong2** [comment]
Thanks for reporting this issue

**Comment by wong2** [comment]
Fixed in v1.2.1
